kind: pipeline
type: kubernetes
name: formulablue

steps:
  - name: Build with Cargo
    image: rust:latest
    commands:
    - cargo build --release

  - name: Deploy to server
    image: ubuntu:latest
    environment:
      DEBIAN_FRONTEND: noninteractive
      SSH_KEY:
        from_secret: ssh_key
    commands:
    - apt update && apt install -y rsync openssh-client dos2unix
    - mkdir -p $HOME/.ssh/
    - eval `ssh-agent`
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null

    - rm -rf $HOME/.ssh/config
    - touch $HOME/.ssh/config
    - echo "Host *\n\tStrictHostKeyChecking no" > $HOME/.ssh/config
    - rsync -ah --progress -e "ssh -i $HOME/.ssh/id_ed25519" target/release/formula_blue droneci@192.168.1.40:/tmp/formula_blue
    - ssh -i $HOME/.ssh/id_ed25519 droneci@192.168.1.40 sudo mv /tmp/formula_blue /usr/local/bin/formula_blue
    - ssh -i $HOME/.ssh/id_ed25519 droneci@192.168.1.40 sudo chmod +x /usr/local/bin/formula_blue
    - ssh -i $HOME/.ssh/id_ed25519 droneci@192.168.1.40 sudo systemctl restart formulablue

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: discord_webhook
      username: Drone CI/CD - FormulaBlue
    when:
      status: [ failure ]

trigger:
  branch:
  - master
